import Navbar from "@/components/navbar/navbar";
import "./globals.css";
import { geistMono, geistSans } from "@/lib/fonts/font";

export const metadata = {
  title: "Games Report | The Best Place for Stay Up to Date for Gaming Information",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0E1217]`}
      >
        <Navbar />
        <div className="p-5 mt-28">
          <div className="w-[85%] mx-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
